version: '3'

services:
  subscan-api:
    image: oap75/subscan-api:latest
    environment: &app_base
      MYSQL_HOST: mysql
      MYSQL_PASS: 'subsocial'
      # Name of the database subscan will connect to and use
      # this db must exist
      MYSQL_DB: 'subscan'
      REDIS_ADDR: redis:6379
      CHAIN_WS_ENDPOINT: 'wss://rpc.polkadot.io'
      # the types file used for the chain as:
      # configs/source/{NETWORK_NODE}.json
      NETWORK_NODE: 'polkadot'
      WEB_HOST: 'http://subscan-api:4399'
      DEPLOY_ENV: 'prod'
    ports:
      - '4399:4399'
    networks:
      explorer:
        ipv4_address: 172.28.1.3

  subscan-observer:
    environment:
      <<: *app_base
    image: oap75/subscan-api:latest
    command: ["python","run.py","substrate"]
    networks:
      explorer:
        ipv4_address: 172.28.1.4 

  subscan-static:
    image: oap75/subscan-static:latest 
    environment:
      NODE_ENV: 'production'
    ports:
      - '3012:80'
    networks:
      explorer:
        ipv4_address: 172.28.1.5        

networks:
  explorer:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16 
