version: '3'

services:

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - 6379:6379
    command:  redis-server --save 
    volumes:
      - ./data/redis:/data
    networks:
      explorer:
        ipv4_address: 172.28.1.1

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: subscan
      MYSQL_ROOT_PASSWORD: subsocial
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      explorer:
        ipv4_address: 172.28.1.2
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


networks:
  explorer:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
